name: malaria_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - joblib=1.1.0
  - jupyter
  - matplotlib=3.5.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - pandas=1.3.5
  - pytest=6.2.5
  - python=3.7.9
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - shap=0.40.0
  - xlsxwriter=3.0.2
